version: '2'

services:
  bokeh:
    restart: always
    build:
      context: .
      args:
        BOKEH_PREFIX: /airss-structures
    image: discover-airss
    command: ["/opt/serve-app.sh"]
    environment:
      PYTHONPATH: '/project'
      SHELL: '/bin/bash'

    volumes:
     - './data:/project/discover-airss/data'
    ports:
      - '3253:5006'
